name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: '40 15 */9 * *'

permissions:
  contents: read

jobs:
  selftest:
    uses: ./.github/workflows/test.yaml
    with:
      working-directory: ./selftest

# vim: set sw=2 sts=2 et :
